<?php

require_once __DIR__ . '/../_init.php';

require __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Spreadsheet.php';



use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// EXPORT ALL ACCOUNTS
if (isset($_GET['action']) && $_GET['action'] === 'export') {

    ob_start();

    // Get all chart of accounts
    $chartOfAccounts = ChartOfAccount::all();

    // Check if $chartOfAccounts is null or empty
    if (empty($chartOfAccounts)) {
        die("No chart of accounts data found.");
    }

    // Create new Spreadsheet object
    $spreadsheet = new Spreadsheet();

    // Set document properties
    $spreadsheet->getProperties()->setCreator('Your App Name')
        ->setLastModifiedBy('Your App Name')
        ->setTitle('Chart of Accounts')
        ->setSubject('Chart of Accounts Export')
        ->setDescription('Chart of Accounts export generated by Your App Name');

    // Add some data
    $sheet = $spreadsheet->getActiveSheet();
    $sheet->setCellValue('A1', 'Account ID');
    $sheet->setCellValue('B1', 'Account Code');
    $sheet->setCellValue('C1', 'Account Type');
    $sheet->setCellValue('D1', 'Account Name');
    $sheet->setCellValue('E1', 'Sub Account Of');
    $sheet->setCellValue('F1', 'Account Description');

    // Add data from database
    $row = 2;
    foreach ($chartOfAccounts as $account) {
        $sheet->setCellValue('A' . $row, $account->id);
        $sheet->setCellValue('B' . $row, $account->account_code);
        $sheet->setCellValue('C' . $row, $account->account_type);
        $sheet->setCellValue('D' . $row, $account->account_name);
        $sheet->setCellValue('E' . $row, $account->sub_account_name);
        $sheet->setCellValue('F' . $row, $account->account_description);
        $row++;
    }

    // Set column widths
    $sheet->getColumnDimension('A')->setWidth(15);
    $sheet->getColumnDimension('B')->setWidth(20);
    $sheet->getColumnDimension('C')->setWidth(20);
    $sheet->getColumnDimension('D')->setWidth(15);
    $sheet->getColumnDimension('E')->setWidth(15);
    $sheet->getColumnDimension('F')->setWidth(15);


    // Create your Excel file
    $writer = new Xlsx($spreadsheet);

    // Set headers for download
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment;filename="chart_of_accounts.xlsx"');
    header('Cache-Control: max-age=0');

    // Save file to output
    // $writer->save('php://output');
    // exit;

    $writer->save('php://output');
    $xlsData = ob_get_contents();
    ob_end_clean();

    $response = array(
        'op' => 'ok',
        'file' => "data:application/vnd.ms-excel;base64," . base64_encode($xlsData)
    );

    die(json_encode($response));
}
